version: '3'
services:
  web:
    image: suhansaha/talib_kite-alpine:latest
    command: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:5000 --reload wsgi:app
    volumes:
      - ./src:/code
    expose:
      - 5000
    depends_on:
      - redis
      - db
    restart: always
  ticker:
    image: suhansaha/talib_kite-alpine:latest
    command: python ticker.py
    volumes:
      - ./src:/code
    expose:
      - 5000
    depends_on:
      - redis
      - db
      - live
    restart: always
  backtest:
    image: suhansaha/talib_kite-alpine
    command: python backtest.py
    volumes:
      - ./src:/code
    expose:
      - 5000
    depends_on:
      - redis
      - db
    restart: always
  live:
    image: suhansaha/talib_kite-alpine
    command: python live.py
    volumes:
      - ./src:/code
    expose:
      - 5000
    depends_on:
      - redis
      - db
    restart: always
  order:
    image: suhansaha/talib_kite-alpine
    command: python order.py
    volumes:
      - ./src:/code
    expose:
      - 5000
    depends_on:
      - redis
      - db
    restart: always
  jupyter:
    image: suhansaha/talib_kite-alpine
    command: jupyter notebook --config=/code/jupyter_notebook_config.py --ip=0.0.0.0 --port=8888
    restart: always
    volumes:
        - ./src:/code
    expose:
        - 8888
  db:
    image: postgres
    volumes:
      - ./db/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=suhan
      - POSTGRES_PASSWORD=suhan005
      - POSTGRES_DB=freedom
    expose:
      - 5432
    ports:
      - 5432:5432
  redis:
    image: "redis:alpine"
    restart: always
    volumes:
      - ./db/redis-data:/var/lib/redis
      - ./db/redis.conf:/usr/local/etc/redis/redis.conf
  nginx:
    build: ./docker/nginx
    expose:
      - 443
      - 80
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl:/etc/nginx/certs
      - ./www:/usr/share/nginx/html
    depends_on:
      - web
      - jupyter
